version: '3.8'

services:
  server:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - database
    networks:
      - komis

  database:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: adm12345
      MARIADB_USER: ${USER}
      MARIADB_PASSWORD: ${PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./database/:/docker-entrypoint-initdb.d/
    networks:
      - komis

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - ADMINER_DESIGN=dracula
      - ADMINER_DEFAULT_SERVER=database
    depends_on:
      - database
    networks:
     - komis

networks:
  komis: