version: '3.8'

services:
  database:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: adm12345
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./database/:/docker-entrypoint-initdb.d/
    networks:
     - komis

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - ADMINER_DESIGN=dracula
      - ADMINER_DEFAULT_SERVER=database
    depends_on:
      - database
    networks:
     - komis

networks:
  komis: